export const CLEAR_LOGIN_EDITOR = 'CLEAR_LOGIN_EDITOR';

export const LOGIN_FIELD_UPDATED = 'LOGIN_FIELD_UPDATED';

export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

export const USER_FETCHED = 'USER_FETCHED';

export const USER_FETCHED_FAILURE = 'USER_FETCHED_FAILURE';

export const LOADING_STATE_ENABLED = 'LOADING_STATE_ENABLED';

export const LOADING_STATE_DISABLED = 'LOADING_STATE_DISABLED';

export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';

export const CATEGORIES_FETCHED_FAILURE = 'CATEGORIES_FETCHED_FAILURE';

export const CATEGORY_FIELD_UPDATED = 'CATEGORY_FIELD_UPDATED';

export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';

export const CLEAR_CATEGORY_EDITOR = 'CLEAR_CATEGORY_EDITOR';

export const CATEGORY_SAVE_ERROR = 'CATEGORY_SAVE_ERROR';

export const CATEGORY_FETCHED = 'CATEGORY_FETCHED';

export const CATEGORY_STATE_CLEARED = 'CATEGORY_STATE_CLEARED';

export const CATEGORY_ADD_MODAL_OPENED = 'CATEGORY_ADD_MODAL_OPENED';

export const CATEGORY_ADD_MODAL_RESET = 'CATEGORY_ADD_MODAL_RESET';

export const CATEGORY_EDIT_MODAL_OPENED= 'CATEGORY_EDIT_MODAL_OPENED';

export const CATEGORY_EDIT_MODAL_RESET = 'CATEGORY_EDIT_MODAL_RESET';
